const DEFAULT_SPORT_STATS = Object.freeze({
    Cricket: [
        "Runs Scored",
        "Wickets Taken",
        "Batting Average",
        "Bowling Economy",
        "Strike Rate",
        "Catches Taken",
        "Run Outs",
        "Sixes Hit",
        "Fours Hit",
        "Balls Faced",
        "Overs Bowled",
        "Dot Balls",
    ],
    Basketball: [
        "Points Scored",
        "Assists",
        "Rebounds",
        "Steals",
        "Blocks",
        "Turnovers",
        "Free Throw Percentage",
        "Three Point Percentage",
        "Minutes Played",
        "Fouls Committed",
    ],
    Football: [
        "Goals Scored",
        "Assists",
        "Shots on Target",
        "Pass Accuracy",
        "Tackles Won",
        "Interceptions",
        "Saves (for Goalkeeper)",
        "Fouls Committed",
        "Yellow Cards",
        "Red Cards",
        "Offsides",
    ],
    Tennis: [
        "Aces",
        "Double Faults",
        "First Serve Percentage",
        "Break Points Won",
        "Unforced Errors",
        "Winners",
        "Total Points Won",
        "Net Points Won",
    ],
    Badminton: [
        "Matches Won",
        "Smash Accuracy",
        "Net Shots Won",
        "Unforced Errors",
        "Drop Shot Success Rate",
        "Service Ace Count",
    ],
    Swimming: [
        "Lap Time",
        "Total Distance Covered",
        "Stroke Rate",
        "Turn Efficiency",
        "Breathing Pattern",
        "Kick Efficiency",
    ],
    Athletics: [
        "100m Sprint Time",
        "Long Jump Distance",
        "High Jump Height",
        "Shot Put Distance",
        "400m Race Time",
        "800m Race Time",
        "Marathon Completion Time",
    ],
    Volleyball: [
        "Spikes Completed",
        "Blocks",
        "Digs",
        "Assists",
        "Aces",
        "Service Errors",
    ],
    Baseball: [
        "Home Runs",
        "Batting Average",
        "RBIs (Runs Batted In)",
        "Strikeouts (Pitcher)",
        "ERA (Earned Run Average)",
        "On Base Percentage",
    ],
    Golf: [
        "Fairways Hit",
        "Greens in Regulation",
        "Putting Accuracy",
        "Sand Saves",
        "Driving Distance",
        "Number of Birdies",
    ],
    Hockey: [
        "Goals Scored",
        "Assists",
        "Shots on Target",
        "Saves (for Goalkeeper)",
        "Penalty Minutes",
        "Faceoffs Won",
    ],
    Table_Tennis: [
        "Total Points Won",
        "Aces",
        "Unforced Errors",
        "Smash Success Rate",
        "Rally Length",
        "Spin Efficiency",
    ],
});

export default DEFAULT_SPORT_STATS;